package design

import (
	. "github.com/goadesign/goa/design" // Use . imports to enable the DSL
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("latex", func() { // API defines the microservice endpoint and
	Title("Secure Latex Compilation API")                           // other global properties. There should be one
	Description("An API for secure compilation of Latex documents") // and exactly one API definition appearing in
	Scheme("http")                                                  // the design.
	Host("localhost:8080")
	Produces("application/json") // Media types generated by the API
	Version("1.0.0")
})

var _ = Resource("latex", func() { // Resources group related API endpoints
	Action("upload", func() {
		Description("Route for uploading the Latex files")
		Routing(POST("/upload"))
		Payload(func() {
			Member("max_downloads", Integer)
			Member("file")
			Member("debug", Boolean)
		})
		Response(OK, "application/json")
		Response(NotAcceptable)
	})

	Action("status", func() {
		Description("Actual compilation status")
		Routing(GET("/status/:uuid"))
		Params(func() {
			Param("uuid", String, "Job UUID")
		})
		Response(OK, "application/json")
		Response(NotFound)
	})

	Action("download", func() {
		Description("Download route for compilation")
		Routing(GET("/download/:uuid"))
		Params(func() {
			Param("uuid", Integer, "Job UUID")
		})
		Response(OK)
		Response(NotFound)
		Response("Too much downloads", func() {
			Description("Compilation had to much downloads")
			Status(400)
			Media("application/json")
		})
	})
})

var LatexArchive = MediaType("application/vnd.texsec.archive", func() {
	Description("Latex file Archive")
	TypeName("LatexArchive")
	Attributes(func() {
		Attribute("uuid", String, "Archive UUID")
		Attribute("filename", String, "Archive filename")
		Attribute("uploaded_at", DateTime, "Upload timestamp")
		Required("uuid", "filename", "uploaded_at")
	})
	View("default", func() {
		Attribute("uuid")
		Attribute("filename")
		Attribute("uploaded_at")
	})
})
