consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  UploadLatexPayload:
    example:
      debug: true
      file: Distinctio cum consequatur.
      max_downloads: 5.76595e+18
    properties:
      debug:
        example: true
        type: boolean
      file:
        example: Distinctio cum consequatur.
        type: string
      max_downloads:
        example: 5.76595e+18
        format: int64
        type: integer
    title: UploadLatexPayload
    type: object
host: localhost:8080
info:
  description: An API for secure compilation of Latex documents
  title: Secure Latex Compilation API
  version: 1.0.0
paths:
  /download/{uuid}:
    get:
      description: Download route for compilation
      operationId: latex#download
      parameters:
      - description: Job UUID
        in: path
        name: uuid
        required: true
        type: integer
      produces:
      - application/json
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Compilation had to much downloads
        "404":
          description: Download was not found
      schemes:
      - http
      summary: download latex
      tags:
      - latex
  /status/{uuid}:
    get:
      description: Actual compilation status
      operationId: latex#status
      parameters:
      - description: Job UUID
        in: path
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
        "404":
          description: UUID was not found
      schemes:
      - http
      summary: status latex
      tags:
      - latex
  /upload:
    post:
      description: Route for uploading the Latex files
      operationId: latex#upload
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UploadLatexPayload'
      responses:
        "200":
          description: OK
        "406":
          description: Upload was not acceptable
      schemes:
      - http
      summary: upload latex
      tags:
      - latex
produces:
- application/json
responses:
  OK:
    description: OK
schemes:
- http
swagger: "2.0"
