// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "latex": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/gianluca311/texsec/api/design
// --out=$(GOPATH)/src/github.com/gianluca311/texsec/api
// --version=v1.1.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// LatexController is the controller interface for the Latex actions.
type LatexController interface {
	goa.Muxer
	Download(*DownloadLatexContext) error
	Status(*StatusLatexContext) error
	Upload(*UploadLatexContext) error
}

// MountLatexController "mounts" a Latex resource controller on the given service.
func MountLatexController(service *goa.Service, ctrl LatexController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewDownloadLatexContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Download(rctx)
	}
	service.Mux.Handle("GET", "/download/:uuid", ctrl.MuxHandler("download", h, nil))
	service.LogInfo("mount", "ctrl", "Latex", "action", "Download", "route", "GET /download/:uuid")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewStatusLatexContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Status(rctx)
	}
	service.Mux.Handle("GET", "/status/:uuid", ctrl.MuxHandler("status", h, nil))
	service.LogInfo("mount", "ctrl", "Latex", "action", "Status", "route", "GET /status/:uuid")

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewUploadLatexContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Upload(rctx)
	}
	service.Mux.Handle("POST", "/upload", ctrl.MuxHandler("upload", h, nil))
	service.LogInfo("mount", "ctrl", "Latex", "action", "Upload", "route", "POST /upload")
}
