// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "latex": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/gianluca311/texsec/api/design
// --out=$(GOPATH)/src/github.com/gianluca311/texsec/api
// --version=v1.1.0-dirty

package app
