// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "latex": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/gianluca311/texsec/api/design
// --out=$(GOPATH)/src/github.com/gianluca311/texsec/api
// --version=v1.1.0-dirty

package app

import (
	"github.com/goadesign/goa"
	"time"
)

// Latex file Archive (default view)
//
// Identifier: application/vnd.texsec.archive; view=default
type LatexArchive struct {
	// Archive filename
	Filename string `form:"filename" json:"filename" xml:"filename"`
	// Upload timestamp
	UploadedAt time.Time `form:"uploaded_at" json:"uploaded_at" xml:"uploaded_at"`
	// Archive UUID
	UUID string `form:"uuid" json:"uuid" xml:"uuid"`
}

// Validate validates the LatexArchive media type instance.
func (mt *LatexArchive) Validate() (err error) {
	if mt.UUID == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "uuid"))
	}
	if mt.Filename == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "filename"))
	}

	return
}
